[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D104",
    "D100",
    "D103",
    "D211",
    "D213",
    "D101",
    "D102",
    "D105",
    "D106",
    "D107",
    "D203",
    "ISC001",
    "COM812",
    "T201",
    "FBT001",
    "E501",
]
